version: '3.3'

services:

  service:
    environment:
      - URL_LIST=${URL_LIST}
      - DOCKER_IMAGE=${DOCKER_IMAGE}
      - DOCKER_TAG=${DOCKER_TAG}
      - DOCKER_STACK=${DOCKER_STACK}
      - DEPLOY_ENV=${DEPLOY_ENV}
    image: $DOCKER_IMAGE:$DOCKER_TAG
    networks:
      - traefik_proxy
    deploy:
      labels:
        - "traefik.port=1313"
        - "traefik.backend=service"
        - "traefik.frontend.rule=Host:$DOCKER_STACK.$DEPLOY_ENV.magnesium.coop,$URL_LIST"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.frontend.passHostHeader=true"
      restart_policy:
        condition: on-failure
   # healthcheck:
   #   test: curl -sS http://127.0.0.1:1313 || exit 1
   #   interval: 5s
   #   timeout: 10s
   #   retries: 3

networks:
  traefik_proxy:
    external: true