version: '3.1'

services:

  mg_webpage:
    build: .
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: password      
    volumes:
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./startup.sh:/startup.sh
    entrypoint: /startup.sh
    links: 
      - mysql

  mysql:
      image: mysql:5.7
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 1000:80
    environment:
      - MYSQL_ROOT_PASSWORD:password
    links: 
      - mysql:db
